default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: railer
  password: 662001

development:
  <<: *default
  database: morningbird_app_api_development

test:
  <<: *default
  database: morningbird_app_api_test

production:
  <<: *default
  database: morningbird_app_production
  username: morningbird_app
  password: <%= ENV["MORNINGBIRD_APP_DATABASE_PASSWORD"] %>
